CREATE TABLE MANAGE(
ID VARCHAR(255) PRIMARY KEY,
TITLE VARCHAR(255),
AUTHOR VARCHAR(255),
PUBLISHER VARCHAR(255),
PRICE INTEGER,
IMAGEURL VARCHAR(255),
COMMENT VARCHAR(255),
EVALUATION INTEGER,
NOWSTATE VARCHAR(255),
PURCHASESTORE VARCHAR(255),
PURCHASEDATE VARCHAR(255)
);